ahp/urls.py
from django.urls import path, include
from ahp.views import *

app_name = 'ahp'

urlpatterns = [
    path('', ahp, name='ahp'),
    path('bobot-aktif/', bobot_aktif, name='bobot_aktif'),
    path('bobot-history/', bobot_history, name='bobot_history'),
    path('biodata/', biodata, name='biodata'),
    path('edit-biodata/', edit_biodata, name='edit_biodata'),
    path('proses-ranking/', proses_ranking, name='proses_ranking'),
    path('buka-beasiswa/', buka_beasiswa, name='buka_beasiswa'),
]

beasiswa/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

from beasiswa.views import *
from beasiswa.authentication import *

urlpatterns = [
    path('admin', admin.site.urls),
    path('', home, name='home'),
    path('dashboard', dashboard, name='dashboard'),
    path('dashboard/ahp/', include("ahp.urls")),
    path('dashboard/user/', include("user.urls")),

    
    ######## Authentication ########
    path('auth-login', login, name='login'),
    path('auth-logout', logout, name='logout'),
    path('ubah-password', ubah_password, name='ubah_password'),
    
    ######## Wildcard untuk URL lainnya ########
    path('<path:path>', views.handle_404, name='handle_404'),  # Atur wildcard untuk menangani URL yang tidak ditemukan
]

############### Media ###############
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/dashboard/admin/mahasiswa_akun_forms.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block content %}
<div class="row mt-4">
  <div class="col-lg-12 col-12 mx-auto position-relative">
    <div class="card">  
      <div class="card-header p-3 pt-2">
        <div class="icon icon-lg icon-shape bg-gradient-dark shadow text-center border-radius-xl mt-n4 me-3 float-start">
          <i class="material-icons opacity-10">person_add</i>
        </div>
        <div class="d-flex justify-content-between align-items-center">
        <h6 class="mb-0">
          {% if mahasiswa %}
          Edit Akun Mahasiswa
          {% else %}
            Tambah Akun Mahasiswa
          {% endif %}
        </h6>
        <a href="{% url "admin_mahasiswa_akun_list" %}" class="btn btn-secondary px-3 py-2 m-0 mt-2"><i class="material-icons">menu_open</i>Kembali</a>
        </div>
      </div>
      <div class="card-body pt-2"> 
        <form method="POST">
          {% csrf_token %}
          <br>
          <div class="input-group input-group-dynamic {% if mahasiswa.user.username %}is-filled{% endif %}">
            <label for="username" class="form-label">NIM (Username)</label>
                {% if mahasiswa.user.id %}
                    <!-- Form untuk edit, menampilkan username mahasiswa yang sedang diedit -->
                    <input type="hidden" name="nim" value="{{ mahasiswa.user.username }}">
                    <input type="text" class="form-control" value="{{ mahasiswa.user.username }}" disabled>
                {% else %}
                    <!-- Form untuk tambah, menampilkan form input untuk NIM -->
                    {{ form.nim }}
                {% endif %}
          </div> <br>
          <!-- First Name -->
          <div class="input-group input-group-dynamic {% if form.first_name.value %}is-filled{% endif %}">
            <label for="first_name" class="form-label">Nama Depan</label>
            {{ form.first_name }}
          </div> <br>
          <!-- Last Name -->
          <div class="input-group input-group-dynamic {% if form.last_name.value %}is-filled{% endif %}">
            <label for="last_name" class="form-label">Nama Belakang</label>
            {{ form.last_name }}
          </div>
          <input type="hidden" name="username" value="{{ form.nim.value }}">
          <input type="hidden" name="password1" value="{{ form.nim.value }}">
          <input type="hidden" name="password2" value="{{ form.nim.value }}">
          <div class="d-flex justify-content-end mt-4">
            <button type="submit" name="button" class="btn bg-gradient-dark m-0 ms-2">Simpan</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/dashboard/admin/mahasiswa_akun_list.html
{% extends "dashboard/base.html" %}
{% load static %}
{% load custom_filters %}
{% block content %}
<div class="row mt-4">
  <div class="col-12">
    <div class="card">
      <!-- Card header -->
      <div class="card-header">
      <div class="d-flex justify-content-between align-items-center">
        <h5 class="mb-0">Akun Mahasiswa</h5> 
        <a class="btn btn-success px-3 py-2 m-0" href="{% url "admin_mahasiswa_akun_tambah" %}"><i class="material-icons">add</i> Tambah</a>
      </div>
      </div>
      <div class="table-responsive">
        <table class="table table-flush" id="datatable-search">
          <thead class="thead-light">
            <tr>
              <th>No</th>
              <th>Nim</th>
              <th>Nama Mahasiswa</th>
              <th class="text-center">Action</th>
            </tr>
          </thead>
          <tbody>
          {% for m in daftar_mahasiswa %}
            <tr> 
              <td class="text-sm font-weight-normal">{{forloop.counter}}</td>
              <td class="text-sm font-weight-normal text-dark">
                {{ m.user.username }}
              </td>
              <td class="text-sm font-weight-normal text-dark">{{m.user.first_name|default:"-"}} {{m.user.last_name|default:"-"}}</td>

              <td class="text-sm font-weight-normal text-center">
                <a class="btn btn-warning px-3 py-2" href="{% url 'admin_mahasiswa_akun_edit' m.user_id %}"><i class="material-icons">edit_note</i> Edit</a>
                <a class="btn btn-danger px-3 py-2" href="{% url 'admin_mahasiswa_akun_hapus' m.user.id %}" onclick="return confirmHapus('{{ m.user.username }}')"><i class="material-icons">delete</i> Hapus</a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock  %}

{% block js %}
  <script src="{% static 'dashboard/assets/js/plugins/datatables.js' %}"></script>
  <script>
    const dataTableSearch = new simpleDatatables.DataTable("#datatable-search", {
      searchable: true,
      fixedHeight: true
    });

    function confirmHapus(nim) {
      return confirm("Apakah Anda yakin ingin menghapus akun dengan NIM: " + nim + "?");
  }
  </script>
{% endblock %}

templates/dashboard/admin/mahasiswa_list.html
{% extends "dashboard/base.html" %}
{% load static %}
{% load custom_filters %}

{% block content %}
<div class="row mt-4">
  <div class="col-12">
    <div class="card">
      <!-- Card header -->
      <div class="card-header">
      <div class="d-flex justify-content-between align-items-center">
        <h5 class="mb-0">Daftar Mahasiswa</h5> 
        {% if perhitungan_selesai %}
        <a href="{% url 'ahp:buka_beasiswa' %}" class="btn btn-info px-3 py-2 m-0"><i class="material-icons">refresh</i>Buka kembali pendaftaran</a>
        {% else %}
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-success px-3 py-2 m-0" data-bs-toggle="modal" data-bs-target="#kuotaModal">
          <i class="material-icons">equalizer</i>Finalisasi Ranking
        </button>
        <!-- Modal -->
        <div class="modal fade" id="kuotaModal" tabindex="-1" role="dialog" aria-labelledby="kuotaModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title font-weight-normal" id="kuotaModalLabel">Jumlah Kuota</h5>
                <button type="button" class="btn-close text-dark" data-bs-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <!-- Gunakan form biasa untuk mengirim data -->
                <form id="kuotaForm" action="{% url 'ahp:proses_ranking' %}" method="POST">
                  {% csrf_token %}
                  <div class="mb-3">
                    <input type="number" class="form-control" id="kuota" name="kuota" placeholder="Masukkan jumlah kuota mahasiswa yang lolos" required>
                  </div>
                  <button type="submit" class="btn bg-gradient-primary">Finalisasi</button>
                </form>
              </div>
            </div>
          </div>
        </div>
        {% endif %}
      </div>
      </div>
      <div class="table-responsive">
        <table class="table table-flush" id="datatable-search">
          <thead class="thead-light">
            <tr>
              {% if perhitungan_selesai %}
              <th>Rank</th>
              {% else %}
              <th>No</th>
              {% endif %}
              <th>Nim</th>
              <th>Nama Mahasiswa</th>
              <th>IPK</th>
              <th>Penghasilan</th>
              <th>Tgg</th>
              <th>Usia</th>
              {% if perhitungan_selesai %}
              <th>Score</th>
              <th>Status</th>
              {% else %}
              <th class="text-center">Action</th>
              {% endif %}
            </tr>
          </thead>
          <tbody>
            {% for m in daftar_mahasiswa %}
                <tr>
                  {% if perhitungan_selesai %}
                  <td class="text-sm font-weight-normal text-dark">
                    {{m.rank}}
                  </td>
                  {% else %}
                    <td class="text-sm font-weight-normal text-dark">
                      {{ forloop.counter }}
                    </td>
                  {% endif %}
                    <td class="text-sm font-weight-normal text-dark">
                      {{ m.user.username }}
                    </td>
                    <td class="text-sm font-weight-normal text-dark">
                        {{ m.user.first_name|default:"-" }} {{ m.user.last_name|default:"-" }}
                    </td>
                    <td class="text-sm font-weight-normal text-dark">
                        {{ m.ipk }}
                    </td>
                    <td class="text-sm font-weight-normal text-dark">
                        Rp {{ m.penghasilan_orang_tua|floatformat:0|intdot }}
                    </td>
                    <td class="text-sm font-weight-normal text-dark">
                        {{ m.jumlah_tanggungan }}
                    </td>
                    <td class="text-sm font-weight-normal text-dark">
                        {{ m.usia }}
                    </td>
                    {% if perhitungan_selesai %}
                    <td class="text-sm font-weight-normal text-dark">
                      {{m.total_score|floatformat:3}}
                    </td>
                    <td class="text-sm font-weight-normal text-dark">
                      {% if m.is_lolos %}
                      <span class="badge rounded-pill bg-success ms-2">Lolos</span>
                      {% elif m.is_lolos == False %}
                      <span class="badge rounded-pill bg-danger ms-2">Ditolak</span>

                      {% else %}
                      <span class="badge rounded-pill bg-danger ms-2">Belum Diproses</span>

                      {% endif %}
                    </td>
                    {% else %}
                    {% endif %}
                    {% if perhitungan_selesai %}
                    {% else %}
                    <td class="text-sm font-weight-normal text-center">
                        <a class="btn btn-warning px-3 py-2" href="{% url 'admin_mahasiswa_list_edit' m.user_id %}"><i class="material-icons">edit_note</i>Edit</a>
                    </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock  %}

{% block js %}
  <script src="{% static 'dashboard/assets/js/plugins/datatables.js' %}"></script>
  <script>
    const dataTableSearch = new simpleDatatables.DataTable("#datatable-search", {
      searchable: true,
      fixedHeight: true
    });
  </script>
{% endblock %}

templates/dashboard/admin/mahasiswa_list_edit.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block content %}
<div class="row mt-4">
  <div class="col-lg-12 col-12 mx-auto position-relative">
    <div class="card">  
      <div class="card-header p-3 pt-2">
        <div class="icon icon-lg icon-shape bg-gradient-dark shadow text-center border-radius-xl mt-n4 me-3 float-start">
          <i class="material-icons opacity-10">interests</i>
        </div>
        <div class="d-flex justify-content-between align-items-center">
          <h6 class="mb-0">Edit Mahasiswa</h6> 
          <a href="{% url "admin_mahasiswa_list" %}" class="btn btn-secondary px-3 py-2 m-0 mt-2"><i class="material-icons">menu_open</i>Kembali</a>
        </div>
      </div>
      <div class="card-body pt-2">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="row">
            <div class="col-6">
              <div class="input-group input-group-static is-filled mb-3 mt-2">
                  <label class="form-label">NIM</label>
                  <input type="text" class="form-control" disabled value="{{ mahasiswa.user.username }}">
              </div>
            </div>
            <div class="col-6">
              <div class="input-group input-group-static is-filled mb-3 mt-2">
                  <label class="form-label">Nama Lengkap</label>
                  <input type="text" class="form-control" disabled value="{{ mahasiswa.user.first_name }} {{mahasiswa.user.last_name}}">
              </div>
            </div>
          </div>
          <div class="input-group input-group-static is-filled mb-4 mt-2">
              <label class="form-label">IPK</label>
              {{ forms.ipk }}
          </div>
          <div class="input-group input-group-static is-filled mb-4 mt-2">
              <label class="form-label">Penghasilan Orang Tua</label>
              {{ forms.penghasilan_orang_tua }}
          </div>
          <div class="input-group input-group-static is-filled mb-4 mt-2">
              <label class="form-label">Jumlah Tanggungan</label>
              {{ forms.jumlah_tanggungan }}
          </div>
          <div class="input-group input-group-static is-filled mb-4 mt-2">
              <label class="form-label">Usia</label>
              {{ forms.usia }}
          </div>
          <div class="d-flex justify-content-start mt-4">
            <button type="submit" name="button" class="btn btn-success px-3 py-2 m-0"><i class="material-icons">save</i>Simpan</button>
          </div>
      </form>      
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block js %}
<script src="{% static 'dashboard/assets/js/plugins/choices.min.js' %}"></script>
<script src="{% static 'dashboard/assets/js/plugins/quill.min.js' %}"></script>
<script src="{% static 'dashboard/assets/js/plugins/flatpickr.min.js' %}"></script>
<script src="{% static 'dashboard/assets/js/plugins/dropzone.min.js' %}"></script>


<script>
    document.addEventListener('DOMContentLoaded', function() {
        var kontenTextarea = document.getElementById('id_konten');
        if (kontenTextarea) {
            kontenTextarea.removeAttribute('required');  // Menghapus atribut 'required'
        }
    });

  if (document.getElementById('choices-multiple-remove-button')) {
    var element = document.getElementById('choices-multiple-remove-button');
    const example = new Choices(element, {
      removeItemButton: true
    });

    example.setChoices(
      [{
          value: 'One',
          label: 'Label One',
          disabled: true
        },
        {
          value: 'Two',
          label: 'Label Two',
          selected: true
        },
        {
          value: 'Three',
          label: 'Label Three'
        },
      ],
      'value',
      'label',
      false,
    );
  }

  if (document.querySelector('.datetimepicker')) {
    flatpickr('.datetimepicker', {
      allowInput: true
    }); // flatpickr
  }
</script>

{% endblock  %}