ahp/urls.py
from django.urls import path, include
from ahp.views import *

app_name = 'ahp'

urlpatterns = [
    path('', ahp, name='ahp'),
    path('bobot-aktif/', bobot_aktif, name='bobot_aktif'),
    path('bobot-history/', bobot_history, name='bobot_history'),
    path('biodata/', biodata, name='biodata'),
    path('edit-biodata/', edit_biodata, name='edit_biodata'),
    path('proses-ranking/', proses_ranking, name='proses_ranking'),
    path('buka-beasiswa/', buka_beasiswa, name='buka_beasiswa'),
]

beasiswa/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

from beasiswa.views import *
from beasiswa.authentication import *

urlpatterns = [
    path('admin', admin.site.urls),
    path('', home, name='home'),
    path('dashboard', dashboard, name='dashboard'),
    path('dashboard/ahp/', include("ahp.urls")),
    path('dashboard/user/', include("user.urls")),

    
    ######## Authentication ########
    path('auth-login', login, name='login'),
    path('auth-logout', logout, name='logout'),
    path('ubah-password', ubah_password, name='ubah_password'),
    
    ######## Wildcard untuk URL lainnya ########
    path('<path:path>', views.handle_404, name='handle_404'),  # Atur wildcard untuk menangani URL yang tidak ditemukan
]

############### Media ###############
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/dashboard/pengguna/biodata.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block content %}

<div class="row mt-4">
  <div class="col-lg-12 col-12 mx-auto position-relative">
    <!-- Card Basic Info -->
    <div class="card" id="basic-info">
      <div class="card-header">
        <div class="d-flex justify-content-between gap-4 align-items-center">
          <h5 class="mb-0">
            {% if request.path == '/dashboard/ahp/edit-biodata/' %}
            Edit Biodata
            {% else %}
            Biodata
            {% endif %}
          </h5> 
          <!-- Tombol Edit atau Kembali -->
          {% if not perhitungan_selesai %}
          <a class="btn {% if request.path == '/dashboard/ahp/edit-biodata/' %}btn-secondary{% else %}btn-warning{% endif %} px-3 py-2 m-0" 
            href="{% if request.path == '/dashboard/ahp/edit-biodata/' %}{% url 'ahp:biodata' %}{% else %}{% url 'ahp:edit_biodata' %}{% endif %}">
            {% if request.path == '/dashboard/ahp/edit-biodata/' %}
              <i class="material-icons">menu_open</i> Kembali
            {% else %}
              <i class="material-icons">edit_note</i> Edit
            {% endif %}
          </a>
          {% endif %}
        </div>
      </div>
      <div class="card-body pt-0">
        <div class="row">
          <div class="col-12">
            <div class="input-group input-group-static is-filled">
              <label>Nama Lengkap</label>
              <input type="text" class="form-control" disabled value="{{ user.first_name }} {{ user.last_name }}">
            </div>
          </div>
        </div>

        <!-- Periksa jika perhitungan sudah selesai -->
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="row mt-2">    
            <div class="col-6">
              <div class="input-group input-group-static is-filled">
                <label>IPK</label>
                {% if perhitungan_selesai == False or mahasiswa_data %}
                <!-- Mode Lihat: Tampilkan IPK dengan disabled -->
                <input type="text" class="form-control" disabled value="{{ mahasiswa_data.ipk|default:"-" }}">
                {% else %}
                  <!-- Mode Edit: Tampilkan form input untuk IPK -->
                  {{ mahasiswa_form.ipk }}
                {% endif %}
              </div>
            </div>
            <div class="col-6">
              <div class="input-group input-group-static is-filled">
                <label>Penghasilan Orang Tua (Rp)</label>
                {% if perhitungan_selesai == False or mahasiswa_data %}
                  <!-- Mode Lihat: Tampilkan penghasilan orang tua dengan disabled jika perhitungan selesai -->
                  <input type="text" class="form-control" disabled value="{{ mahasiswa_data.penghasilan_orang_tua|default:"-" }}">
                {% else %}
                  <!-- Mode Edit: Tampilkan form input untuk penghasilan orang tua -->
                  {{ mahasiswa_form.penghasilan_orang_tua }}
                {% endif %}
              </div>
            </div>
          </div>
      
          <div class="row mt-2">
            <div class="col-6">
              <div class="input-group input-group-static is-filled">
                <label>Jumlah Tanggungan</label>
                {% if perhitungan_selesai == False or mahasiswa_data %}
                  <!-- Mode Lihat: Tampilkan jumlah tanggungan dengan disabled jika perhitungan selesai -->
                  <input type="text" class="form-control" disabled value="{{ mahasiswa_data.jumlah_tanggungan|default:"-" }}">
                {% else %}
                  <!-- Mode Edit: Tampilkan form input untuk jumlah tanggungan -->
                  {{ mahasiswa_form.jumlah_tanggungan }}
                {% endif %}
              </div>
            </div>
            <div class="col-6">
              <div class="input-group input-group-static is-filled">
                <label>Usia (tahun)</label>
                {% if perhitungan_selesai == False or mahasiswa_data %}
                  <!-- Mode Lihat: Tampilkan usia dengan disabled jika perhitungan selesai -->
                  <input type="text" class="form-control" disabled value="{{ mahasiswa_data.usia|default:"-" }}">
                {% else %}
                  <!-- Mode Edit: Tampilkan form input untuk usia -->
                  {{ mahasiswa_form.usia }}
                {% endif %}
              </div>
            </div>
          </div>

          <!-- Tombol Simpan hanya akan tampil jika perhitungan belum selesai -->
          {% if not mahasiswa_data %}
            <button type="submit" class="btn btn-success px-3 py-2 m-0 mt-3"><i class="material-icons">save</i> Simpan</button>
          {% endif %}
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block js %}
<script src="{% static 'dashboard/assets/js/plugins/choices.min.js' %}"></script>
<script src="{% static 'dashboard/assets/js/plugins/quill.min.js' %}"></script>
<script src="{% static 'dashboard/assets/js/plugins/flatpickr.min.js' %}"></script>
<script src="{% static 'dashboard/assets/js/plugins/dropzone.min.js' %}"></script>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        var kontenTextarea = document.getElementById('id_konten');
        if (kontenTextarea) {
            kontenTextarea.removeAttribute('required');  // Menghapus atribut 'required'
        }
    });

    if (document.getElementById('choices-multiple-remove-button')) {
        var element = document.getElementById('choices-multiple-remove-button');
        const example = new Choices(element, {
          removeItemButton: true
        });

        example.setChoices(
          [{
              value: 'One',
              label: 'Label One',
              disabled: true
            },
            {
              value: 'Two',
              label: 'Label Two',
              selected: true
            },
            {
              value: 'Three',
              label: 'Label Three'
            },
          ],
          'value',
          'label',
          false,
        );
    }

    if (document.querySelector('.datetimepicker')) {
        flatpickr('.datetimepicker', {
          allowInput: true
        }); // flatpickr
    }
</script>

{% endblock %}

templates/dashboard/pengguna/user_list.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block content %}
<div class="row mt-4">
        <div class="col-12">
          <div class="card">
            <!-- Card header -->
            <div class="card-header">
            <div class="d-flex justify-content-between align-items-center">
              <h5 class="mb-0">Daftar User</h5> 
            </div>
            </div>
            <div class="table-responsive">
              <table class="table table-flush" id="datatable-search">
                <thead class="thead-light">
                  <tr>
                    <th>No</th>
                    <th>Username</th>
                    <th>Nama Lengkap</th>
                    <th>Is Staff</th>
                    <th class="text-center">Groups</th>
                    <th class="text-center">Action</th>
                  </tr>
                </thead>
                <tbody>
                {% for u in daftar_user %}
                  <tr>
                    <td class="text-sm font-weight-normal">{{forloop.counter}}</td>
                    <td class="text-sm font-weight-normal">
                      <span class="badge badge-success">{{u.username}}</span> 
                    </td>
                    <td class="text-sm font-weight-normal text-dark">{{u.first_name|default:"-"}} {{u.last_name|default:"-"}}</td>
                    <td class="text-sm font-weight-normal">
                      
                      {% if u.is_staff %}
                        <i class="material-icons badge badge-sm rounded-pill bg-success">done</i>
                      {% else %}
                        <i class="material-icons badge badge-sm rounded-pill bg-danger">close</i>
                      {% endif %}
                    </td>
                    <td class="text-sm font-weight-normal text-center">
                      {% for group in u.groups.all %}
                        <span class="badge badge-dark">{{ group.name }}</span>
                      {% empty %}
                        <span class="badge badge-dark">-</span>
                      {% endfor %}
                    </td>
                    <td class="text-sm font-weight-normal text-center">
                      <a class="btn btn-warning px-3 py-2" href=""><i class="material-icons">edit_note</i> Edit</a>
                      <a class="btn btn-danger px-3 py-2" onClick="return confirm('Yakin ingin menghapus?')" href=""><i class="material-icons">delete</i> Hapus</a>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
{% endblock  %}

{% block js %}
  <script src="{% static 'dashboard/assets/js/plugins/datatables.js' %}"></script>
  <script>
    const dataTableSearch = new simpleDatatables.DataTable("#datatable-search", {
      searchable: true,
      fixedHeight: true
    });
  </script>
{% endblock %}