ahp/urls.py
from django.urls import path, include
from ahp.views import *

app_name = 'ahp'

urlpatterns = [
    path('', ahp, name='ahp'),
    path('bobot-aktif/', bobot_aktif, name='bobot_aktif'),
    path('bobot-history/', bobot_history, name='bobot_history'),
    path('biodata/', biodata, name='biodata'),
    path('edit-biodata/', edit_biodata, name='edit_biodata'),
    path('proses-ranking/', proses_ranking, name='proses_ranking'),
    path('buka-beasiswa/', buka_beasiswa, name='buka_beasiswa'),
]

beasiswa/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

from beasiswa.views import *
from beasiswa.authentication import *

urlpatterns = [
    path('admin', admin.site.urls),
    path('', home, name='home'),
    path('dashboard', dashboard, name='dashboard'),
    path('dashboard/ahp/', include("ahp.urls")),
    path('dashboard/user/', include("user.urls")),

    
    ######## Authentication ########
    path('auth-login', login, name='login'),
    path('auth-logout', logout, name='logout'),
    path('ubah-password', ubah_password, name='ubah_password'),
    
    ######## Wildcard untuk URL lainnya ########
    path('<path:path>', views.handle_404, name='handle_404'),  # Atur wildcard untuk menangani URL yang tidak ditemukan
]

############### Media ###############
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/dashboard/index.html
{% extends "dashboard/base.html" %}
{% load static %}
{% load auth_extras %}

{% block content %}
{% if user.is_authenticated %}
  {% if user|has_group:"Admin" or user|has_group:"SuperAdmin" %}
  <div class="row">
    <div class="col-lg-3 col-md-6 col-sm-6 mt-lg-0 mt-4">
      <div class="card ">
        <div class="card-header p-3 pt-2 bg-transparent">
          <div class="icon icon-lg icon-shape bg-gradient-primary shadow-primary text-center border-radius-xl mt-n4 position-absolute">
            <i class="material-icons opacity-10">person</i>
          </div>
          <div class="text-end pt-1">
            <p class="text-sm mb-0 text-capitalize ">Jumlah Mahasiswa</p>
            <h4 class="mb-0 ">{{total_mahasiswa}}</h4>
          </div>
        </div>
        <hr class="horizontal my-0 dark">
      </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-6 mt-lg-0 mt-4">
      <div class="card ">
        <div class="card-header p-3 pt-2 bg-transparent">
          <div class="icon icon-lg icon-shape bg-gradient-info shadow-info text-center border-radius-xl mt-n4 position-absolute">
            <i class="material-icons opacity-10">person_add_alt</i>
          </div>
          <div class="text-end pt-1">
            <p class="text-sm mb-0 text-capitalize ">Jumlah Pendaftar</p>
            <h4 class="mb-0 ">{{total_pendaftar}}</h4>
          </div>
        </div>
        <hr class="horizontal my-0 dark">
      </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-6 mt-lg-0 mt-4">
      <div class="card  mb-2">
        <div class="card-header p-3 pt-2 bg-transparent">
          <div class="icon icon-lg icon-shape bg-gradient-success shadow-success text-center border-radius-xl mt-n4 position-absolute">
            <i class="material-icons opacity-10">how_to_reg</i>
          </div>
          <div class="text-end pt-1">
            <p class="text-sm mb-0 text-capitalize ">Jumlah Lolos</p>
            {% if perhitungan_selesai %}
            <h4 class="mb-0 ">{{total_lolos}}</h4>
            {% else %}
            <p class="mb-1 mt-1 text-md fw-bolder text-dark">Belum dihitung</p>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-6 mt-lg-0 mt-4">
      <div class="card  mb-2">
        <div class="card-header p-3 pt-2 bg-transparent">
          <div class="icon icon-lg icon-shape bg-gradient-dark shadow-dark text-center border-radius-xl mt-n4 position-absolute">
            <i class="material-icons opacity-10">person_off</i>
          </div>
          <div class="text-end pt-1">
            <p class="text-sm mb-0 text-capitalize ">Jumlah Ditolak</p>
            {% if perhitungan_selesai %}
            <h4 class="mb-0 ">{{total_ditolak}}</h4>
            {% else %}
            <p class="mb-1 mt-1 text-md fw-bolder text-dark">Belum dihitung</p>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
    <div class="col-8 mt-3">
      <div class="card h-100">
        <div class="card-header pb-0 p-3">
          <h6 class="mb-0">Statistik Pendaftar</h6>
        </div>
        <div class="card-body pb-0 p-3">
          <ul class="list-group">
            <li class="list-group-item border-0 d-flex align-items-center px-0 mb-0">
              <div class="w-100">
                <div class="d-flex mb-2">
                  <span class="me-2 text-sm text-capitalize">Jumlah Mahasiswa</span>
                  <span class="ms-auto text-sm">100%</span>
                </div>
                <div>
                  <div class="progress progress-md">
                    <div style="width:100% !important;" class="progress-bar bg-gradient-primary" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                </div>
              </div>
            </li>
            <li class="list-group-item border-0 d-flex align-items-center px-0 mb-2">
              <div class="w-100">
                <div class="d-flex mb-2">
                  <span class="me-2 text-sm text-capitalize">Jumlah Pendaftar</span>
                  <span class="ms-auto text-sm">{{persenan_daftar|floatformat:0}}%</span>
                </div>
                <div>
                  <div class="progress progress-md">
                    <div style="width: {{persenan_daftar|floatformat:0}}% !important;" class="progress-bar bg-gradient-info" role="progressbar"></div>
                  </div>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-4 mt-3">
      <div class="card h-100">
        <div class="card-header pb-0 p-3">
          <div class="d-flex justify-content-between">
            <h6 class="mb-0">Statistik Penerimaan</h6>
            </button>
          </div>
        </div>
        <div class="card-body pb-0 pt-0 p-3">
          <div class="row">
            <div class="col-7 text-start">
              <div class="chart">
                {% if perhitungan_selesai %}
                <canvas id="chart-pie" class="chart-canvas" height="200"></canvas>
              </div>
              {% else %}
              <span class="text-dark text-sm mt-5">Data Belum Dihitung</span>
              {% endif %}
            </div>
            <div class="col-5 my-auto">
              <span class="badge badge-md badge-dot me-4 d-block text-start">
                <i class="bg-success"></i>
                <span class="text-dark text-xs">Jumlah Lolos</span>
              </span>
              <span class="badge badge-md badge-dot me-4 d-block text-start">
                <i class="bg-dark"></i>
                <span class="text-dark text-xs">Jumlah Ditolak</span>
              </span>
            </div>
          </div>
        </div>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
  {% if user|has_group:"User" %}
    {% if perhitungan_selesai %}
    <div class="alert alert-danger text-white" role="alert">
      <span class="text-sm">Pendaftaran Sudah ditutup. Silahkan cek status dengan tombol disamping</span>
      <button type="button" class="btn btn-info px-3 py-2 m-0 ms-1" data-bs-toggle="modal" data-bs-target="#cekModal">
        cek
      </button>
      <!-- Modal -->
      <div class="modal fade" id="cekModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title font-weight-normal" id="exampleModalLabel">Pengumuman</h5>
              <button type="button" class="btn-close text-dark" data-bs-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <h3 class="text-center text-dark">
                {% if mahasiswa_data.is_lolos == 1 %}
                    Selamat Anda Lolos! <br>
                    Ranking: {{mahasiswa_data.rank}}
                {% elif mahasiswa_data.is_lolos == 0 %}
                    Maaf Anda Ditolak! <br>
                    Ranking: {{mahasiswa_data.rank}}
                {% else %}
                    Anda Belum Mendaftar
                {% endif %}
            </h3>
            </div>
            <div class="modal-footer d-flex justify-content-center align-items-center">
              <button type="button" class="btn bg-gradient-secondary " data-bs-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% else %}
    <div class="alert alert-success text-white" role="alert">
      <span class="text-sm">Pendaftaran sudah dibuka. Silahkan melengkapi biodata!</span>
    </div>
    {% endif %}
      <div class="row">
        <div class="col-12">
          <div class="card mb-4">
            <div class="card-header pb-0">
              <h6>Syarat Beasiswa</h6>
            </div>
            <div class="card-body px-0 pt-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center mb-0">
                  <thead>
                    <tr>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Kriteria</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Keterangan</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>
                        <span class="badge badge-primary mb-0 px-3 py-1 ms-3">IPK</span>
                      </td>
                      <td>
                        <p class="text-sm font-weight-normal mb-0">Harus diantara 3.00 hingga 4.00</p>
                      </td>
                    </tr>
                    <tr>
                      <td>
                        <span class="badge badge-info mb-0 px-3 py-1 ms-3">Penghasilan Orang Tua</span>
                      </td>
                      <td>
                        <p class="text-sm font-weight-normal mb-0">Harus diantara Rp1.500.000 hingga Rp6.000.000</p>
                      </td>
                    </tr>
                    <tr>
                      <td>
                        <span class="badge badge-success mb-0 px-3 py-1 ms-3">Jumlah Tanggungan</span>
                      </td>
                      <td>
                        <p class="text-sm font-weight-normal mb-0">Harus diantara 1 hingga 6 orang</p>
                      </td>
                    </tr>
                    <tr>
                      <td>
                        <span class="badge badge-warning mb-0 px-3 py-1 ms-3">Usia</span>
                      </td>
                      <td>
                        <p class="text-sm font-weight-normal mb-0">Harus diantara 18 hingga 30 tahun</p>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
        {% comment %} <div class="col-4">
          <div class="card mb-4">
            <div class="card-header pb-0">
              <h6>Syarat Beasiswa</h6>
            </div>
            <div class="card-body px-0 pt-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center mb-0">
                  <thead>
                    <tr>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Kriteria</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Keterangan</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>
                        <span class="badge badge-primary mb-0 px-3 py-1 ms-3">IPK</span>
                      </td>
                      <td>
                        <p class="text-sm font-weight-normal mb-0">Harus diantara 3.00 hingga 4.00</p>
                      </td>
                    </tr>
                    <tr>
                      <td>
                        <span class="badge badge-info mb-0 px-3 py-1 ms-3">Penghasilan Orang Tua</span>
                      </td>
                      <td>
                        <p class="text-sm font-weight-normal mb-0">Harus diantara Rp1.500.000 hingga Rp6.000.000</p>
                      </td>
                    </tr>
                    <tr>
                      <td>
                        <span class="badge badge-success mb-0 px-3 py-1 ms-3">Jumlah Tanggungan</span>
                      </td>
                      <td>
                        <p class="text-sm font-weight-normal mb-0">Harus diantara 1 hingga 6 orang</p>
                      </td>
                    </tr>
                    <tr>
                      <td>
                        <span class="badge badge-warning mb-0 px-3 py-1 ms-3">Usia</span>
                      </td>
                      <td>
                        <p class="text-sm font-weight-normal mb-0">Harus diantara 18 hingga 30 tahun</p>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div> {% endcomment %}
      </div>
  {% endif %}
{% endif %}
{% endblock  %}

{% block js %}
<script>
  var ctx2 = document.getElementById("chart-pie").getContext("2d");
    // Pie chart
    new Chart(ctx2, {
      type: "pie",
      data: {
        labels: ['Jumlah Lolos', 'Jumlah Ditolak'],
        datasets: [{
          label: "Projects",
          weight: 9,
          cutout: 0,
          tension: 0.9,
          pointRadius: 2,
          borderWidth: 1,
          backgroundColor: ['#4CAF50', '#344767'],
          data: [{{ total_lolos }}, {{ total_ditolak }}],
          fill: false
        }],
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          legend: {
            display: false,
          }
        },
        interaction: {
          intersect: false,
          mode: 'index',
        },
        scales: {
          y: {
            grid: {
              drawBorder: false,
              display: false,
              drawOnChartArea: false,
              drawTicks: false,
              color: '#c1c4ce5c'
            },
            ticks: {
              display: false
            }
          },
          x: {
            grid: {
              drawBorder: false,
              display: false,
              drawOnChartArea: false,
              drawTicks: false,
              color: '#c1c4ce5c'
            },
            ticks: {
              display: false,
            }
          },
        },
      },
    });

</script>
{% endblock %}

templates/dashboard/menu.html
{% load static %}
{% load auth_extras %}
  <aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark" id="sidenav-main">
    <div class="sidenav-header">
      <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
      <a class="navbar-brand m-0" href=" https://demos.creative-tim.com/material-dashboard-pro/pages/dashboards/analytics.html " target="_blank">
        <img src="{% static 'landingpage/assets/img/school.png' %}" class="navbar-brand-img h-100" alt="main_logo">
        <span class="ms-1 font-weight-bold text-white">BeasiswaKu</span>
      </a>
    </div>
    <hr class="horizontal light mt-0 mb-2">
    <div class="collapse navbar-collapse  w-auto h-auto max-height-vh-100 h-100" id="sidenav-collapse-main">
      <ul class="navbar-nav">
        <li class="nav-item mb-2 mt-0">
          <a data-bs-toggle="collapse" href="#ProfileNav" class="nav-link {% if request.path == '/ubah-password' %}active{% endif %} text-white" aria-controls="ProfileNav" role="button" aria-expanded="false">
            <img src="{% static 'dashboard/assets/img/team-3.jpg' %}" class="avatar">
            <span class="nav-link-text ms-2 ps-1">{{ user }}</span>
          </a>          
          <div class="collapse {% if request.path == '/ubah-password' %}show{% endif %}" id="ProfileNav">
            <ul class="nav">
              <li class="nav-item">
                <a class="nav-link text-white " href="/auth-logout">
                  <i class="material-icons-round">power_settings_new</i>
                  <span class="sidenav-normal  ms-3  ps-1"> Logout </span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if request.path == '/ubah-password' %}active{% endif %} text-white " href="{% url "ubah_password" %}">
                  <i class="material-icons-round">lock_reset</i>
                  <span class="sidenav-normal  ms-3  ps-1"> Ubah Password </span>
                </a>
              </li>
            </ul>
          </div>
        </li>
        <hr class="horizontal light ms-0 me-0 mt-0 mb-3" />
        <li class="nav-item">
          <a href="{% url "dashboard" %}" class="nav-link text-white {% if request.path == '/dashboard' %}active{% endif %}" aria-controls="pagesExamples" role="button" aria-expanded="false">
            <i class="material-icons-round {% if page.brand == 'RTL' %}ms-2{% else %} me-2{% endif %}">dashboard</i>
            <span class="nav-link-text ms-2 ps-1">Dashboard</span>
          </a>
        </li>
        <hr class="horizontal light mb-3" />
        {% if user.is_authenticated and user|has_group:"SuperAdmin" %}
        <li class="nav-item">
          <h6 class="ps-4  ms-2 text-uppercase text-xs font-weight-bolder text-white">superadmin</h6>
        </li>
        <li class="nav-item">
          <a data-bs-toggle="collapse" href="#Akun" class="nav-link text-white {% if request.path == '/dashboard/user/superadmin/admin/list' or request.path == '/dashboard/user/admin/mahasiswa/akun-list' or request.path == '/dashboard/user/superadmin/admin/tambah' or request.path == '/dashboard/user/admin/mahasiswa/akun-tambah' or '/dashboard/user/superadmin/admin/edit/' in request.path or '/dashboard/user/admin/mahasiswa/akun-edit/' in request.path %}active{% endif %}" aria-controls="Akun" role="button" aria-expanded="false">
            <i class="material-icons-round {% if page.brand == 'RTL' %}ms-2{% else %} me-2{% endif %}">account_circle</i>
            <span class="nav-link-text ms-2 ps-1">Akun</span>
          </a>
          <div class="collapse {% if request.path == '/dashboard/user/superadmin/admin/list' or request.path == '/dashboard/user/superadmin/admin/tambah' or request.path == '/dashboard/user/admin/mahasiswa/akun-list' or request.path == '/dashboard/user/admin/mahasiswa/akun-tambah' or '/dashboard/user/superadmin/admin/edit/' in request.path or '/dashboard/user/admin/mahasiswa/akun-edit/' in request.path %}show{% endif %}" id="Akun">
            <ul class="nav">
              <li class="nav-item">
                <a class="nav-link text-white {% if request.path == '/dashboard/user/superadmin/admin/list' or request.path == '/dashboard/user/superadmin/admin/tambah' or '/dashboard/user/superadmin/admin/edit/' in request.path %}active{% endif %}" aria-expanded="false" href="{% url "superadmin_admin_list" %}">
                  <i class="material-icons-round {% if page.brand == 'RTL' %}ms-2{% else %} me-2{% endif %}">how_to_reg</i>
                  <span class="sidenav-normal  ms-2  ps-1"> Akun Admin <b class="caret"></b></span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-white {% if request.path == '/dashboard/user/admin/mahasiswa/akun-list' or request.path == '/dashboard/user/admin/mahasiswa/akun-tambah' or '/dashboard/user/admin/mahasiswa/akun-edit/' in request.path %}active{% endif %}" aria-expanded="false" href="{% url "admin_mahasiswa_akun_list" %}">
                  <i class="material-icons-round {% if page.brand == 'RTL' %}ms-2{% else %} me-2{% endif %}">diversity_3</i>
                  <span class="sidenav-normal  ms-2  ps-1"> Akun Mahasiswa <b class="caret"></b></span>
                </a>
              </li>
            </ul>
          </div>
        </li>
        <li class="nav-item">
          <a data-bs-toggle="collapse" href="#Perhitungan" class="nav-link text-white {% if request.path == '/dashboard/ahp/' or request.path == '/dashboard/ahp/bobot-aktif/' %}active{% endif %}" aria-controls="Perhitungan" role="button" aria-expanded="false">
            <i class="material-icons-round {% if page.brand == 'RTL' %}ms-2{% else %} me-2{% endif %}">calculate</i>
            <span class="nav-link-text ms-2 ps-1">Perhitungan</span>
          </a>
          <div class="collapse {% if request.path == '/dashboard/ahp/' or request.path == '/dashboard/ahp/bobot-aktif/' or request.path == '/dashboard/ahp/bobot-history/' %}show{% endif %}" id="Perhitungan">
            <ul class="nav">
              <li class="nav-item">
                <a class="nav-link text-white {% if request.path == '/dashboard/ahp/' %}active{% endif %}" aria-expanded="false" href="{% url "ahp:ahp" %}">
                  <i class="material-icons-round {% if page.brand == 'RTL' %}ms-2{% else %} me-2{% endif %}">grid_4x4</i>
                  <span class="sidenav-normal  ms-2  ps-1"> Matriks <b class="caret"></b></span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-white {% if request.path == '/dashboard/ahp/bobot-aktif/' %}active{% endif %}" aria-expanded="false" href="{% url "ahp:bobot_aktif" %}">
                  <i class="material-icons-round {% if page.brand == 'RTL' %}ms-2{% else %} me-2{% endif %}">check_circle_outline</i>
                  <span class="sidenav-normal  ms-2  ps-1"> Bobot Aktif <b class="caret"></b></span>
                </a>
              </li>
            </ul>
          </div>
        </li>
        <li class="nav-item">
          <a href="{% url "admin_mahasiswa_list" %}" class="nav-link text-white {% if request.path == '/dashboard/user/admin/mahasiswa/list' or '/dashboard/user/admin/mahasiswa/list-edit/' in request.path %}active{% endif %}" aria-controls="basicExamples" role="button" aria-expanded="false">
            <i class="material-icons-round {% if page.brand == 'RTL' %}ms-2{% else %} me-2{% endif %}">library_books</i>
            <span class="nav-link-text ms-2 ps-1">Daftar Mahasiswa</span>
          </a>
        </li>
        {% endif %}
        {% if user.is_authenticated and user|has_group:"Admin" %}
        <li class="nav-item">
          <h6 class="ps-4  ms-2 text-uppercase text-xs font-weight-bolder text-white">admin</h6>
        </li>
        <li class="nav-item">
          <a href="{% url "admin_mahasiswa_akun_list" %}" class="nav-link text-white {% if request.path == '/dashboard/user/admin/mahasiswa/akun-list'  or request.path == '/dashboard/user/admin/mahasiswa/akun-tambah' or '/dashboard/user/admin/mahasiswa/akun-edit/' in request.path %}active{% endif %}" aria-controls="basicExamples" role="button" aria-expanded="false">
            <i class="material-icons-round {% if page.brand == 'RTL' %}ms-2{% else %} me-2{% endif %}">account_circle</i>
            <span class="nav-link-text ms-2 ps-1">Akun Mahasiswa</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url "admin_mahasiswa_list" %}" class="nav-link text-white {% if request.path == '/dashboard/user/admin/mahasiswa/list' or '/dashboard/user/admin/mahasiswa/list-edit/' in request.path %}active{% endif %}" aria-controls="basicExamples" role="button" aria-expanded="false">
            <i class="material-icons-round {% if page.brand == 'RTL' %}ms-2{% else %} me-2{% endif %}">library_books</i>
            <span class="nav-link-text ms-2 ps-1">Daftar Mahasiswa</span>
          </a>
        </li>
        {% endif %}
        {% if user.is_authenticated and user|has_group:"User" %}
        <li class="nav-item">
          <h6 class="ps-4  ms-2 text-uppercase text-xs font-weight-bolder text-white">user</h6>
        </li>
        <li class="nav-item mb-3">
          <a href="{% url "ahp:biodata" %}" class="nav-link text-white {% if request.path == '/dashboard/ahp/biodata/' or request.path == '/dashboard/ahp/edit-biodata/' %}active{% endif %}" aria-controls="basicExamples" role="button" aria-expanded="false">
            <i class="material-icons-round {% if page.brand == 'RTL' %}ms-2{% else %} me-2{% endif %}">app_registration</i>
            <span class="nav-link-text ms-2 ps-1">Biodata</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </div>
    
  </aside>

templates/dashboard/ubah_password.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block content %}
<div class="row mt-4">
  <div class="col-lg-12 col-12 mx-auto position-relative">
    <div class="card">  
      <div class="card-header p-3 pt-2">
        <div class="icon icon-lg icon-shape bg-gradient-dark shadow text-center border-radius-xl mt-n4 me-3 float-start">
          <i class="material-icons opacity-10">password</i>
        </div>
        <h6 class="mb-0">Ubah Password</h6>
      </div>
      <div class="card-body pt-2"> 
        <form method="POST">
          {% csrf_token %}
          <br>
          <div class="input-group input-group-dynamic">
            <label for="username" class="form-label">Password Sekarang</label>
                {{form.current_password}}
          </div> <br>
          <div class="input-group input-group-dynamic">
            <label for="first_name" class="form-label">Password Baru</label>
            {{ form.new_password }}
          </div> <br>
          <div class="input-group input-group-dynamic">
            <label for="last_name" class="form-label">Konfirmasi password</label>
            {{ form.confirm_password }}
          </div>
          <div class="d-flex justify-content-end mt-4">
            <button type="submit" name="button" class="btn bg-gradient-dark m-0 ms-2">Simpan</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}